### PR TITLE
Added docker-compose file

### PR DESCRIPTION
**Pull request by divyanshbhowmick**
Solves: #15 

TODOS:
- Need to check if we can only import required depdency for celery service.

@arpanpreneur please review

P.S: Here's my Birthday treat to you, hope it makes you happy 😁 😜😜

### CODE REVIEW

**Comment by jahanvipandey** [comment]
nicely done!!!

**Comment by arpanpreneur** [comment]
Hi @divyanshbhowmick , Thank you so much for your great work on your birthday. 

Just need a few changes however

1. We can just have one Dockerfile instead of two, since the environment for Celery and the Webserver is exactly the same. We can just omit mentioning a CMD in the dockerfile and give the entrypoint from the compose entry.
2. In production we can't run `python manage.py runserver` because it is a single threaded-single request development web server. We will need to use Gunicorn.
3. We need the database (Postgres), Redis, Nginx (with proxy config for serving static files and media files) alongside the celery and app_server services you have already created. We should not be exposing the ports, except for the final nginx. Others should refer each other with the hostnames (service names) within the Docker network.

Once again thank you for the effort you have put in. Just the above changes and we are good to merge this.

**Comment by arpanpreneur** [comment]
To make your work simpler, let me put in the Dockerfile for Python Project. Even I copy and paste these to my new project nowadays.

Sample Dockerfile I use in my other services made with Django (works perfectly on Azure Container Apps).

```
# Dockerfile
# pull official base image
FROM python:3.10

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip setuptools
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install -y nodejs npm
RUN node -v
RUN npm -v

# create user for the Django project
RUN useradd -ms /bin/bash askmydata

# set current user
USER askmydata

# set work directory
WORKDIR /home/askmydata

# copy and install pip requirements
COPY --chown=askmydata ./requirements.txt /home/askmydata/requirements.txt
COPY --chown=askmydata ./package.json /home/askmydata/package.json
COPY --chown=askmydata ./package-lock.json /home/askmydata/package-lock.json
ENV PATH /home/askmydata/.local/bin:$PATH
RUN pip install --user -r /home/askmydata/requirements.txt
RUN npm install
RUN npm install --only=dev


# copy Django project files
COPY --chown=askmydata . /home/askmydata/
RUN npm run build-react-code

RUN ["chmod", "+x", "/home/askmydata/docker-entrypoint-gunicorn.sh"]
RUN ["chmod", "+x", "/home/askmydata/docker-entrypoint-celery.sh"]
```

Where `docker-entrypoint-gunicorn.sh` is:
```
python manage.py collectstatic --no-input
python manage.py migrate
gunicorn --workers 3 --bind 0.0.0.0:8000 --timeout 120 askmydata_server.wsgi:application
```

And `docker-entrypoint-celery.sh` be like:
```
celery -A askmydata_server worker -l info --concurrency=2
```

Please change the Project Names on this from `askmydata_server` to `llmine_core`. Also since we don't yet have JS pipelines like I have in other projects you can remove the NPM related changes. Apart from this the redis, postgres and nginx are something you can just pull from dockerhub. @divyanshbhowmick

**Comment by divyanshbhowmick** [comment]
I've addressed the reivew comments!! @arpanpreneur 

**_One doubt:_** For celery service, I was trying to use the REDIS_URL defined in the .sample.env file and passing the same (referencing ${REDIS_URL}) for CELERY_BROKER_URL but it wasn't working. Celery was taking the transport url as redis://localhost:6379/0 instead of redis://redis:6379/0.
Do, Let me know if you are aware of this issue.

**Review by arpanpreneur — APPROVED** [review]
LGTM

**Pull request merged**
